<a href="https://colab.research.google.com/github/AtharshKrishnamoorthy/Python-codes/blob/main/PYTHON_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Selection operation:

# Program to check if a number is positive or negative

num = int(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

# Iterartive operation :

# Program to print the square of numbers from 1 to 5

for i in range(1, 6):
    square = i ** 2
    print(f"The square of {i} is {square}.")


Enter a number: 7
The number is positive.
The square of 1 is 1.
The square of 2 is 4.
The square of 3 is 9.
The square of 4 is 16.
The square of 5 is 25.


In [ ]:
# Odd - factorial , even - palindrome
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

def is_palindrome(n):
    n = str(n)
    return n == n[::-1]

def count_digits(n):
    return len(str(n))

num = int(input("Enter an integer: "))

if num % 2 == 1:
    fact = factorial(num)
    digit_count = count_digits(fact)
    print(f"The factorial of {num} is: {fact}")
    print(f"The number of digits in the factorial is: {digit_count}")
else:
    if is_palindrome(num):
        print(f"The number {num} is a palindrome.")
    else:
        print(f"The number {num} is not a palindrome.")


Enter an integer: 5
The factorial of 5 is: 120
The number of digits in the factorial is: 3


In [ ]:
# Strings and its operations:

# Concatenating strings:

string1 = "Hello"
string2 = "World"
concatenated_string = string1 + " " + string2
print(concatenated_string)

# String slicing:

my_string = "Hello, World!"
print(my_string[7:12])

# Converting case :

my_string = "Hello, World!"
print(my_string.lower())
print(my_string.upper())

# String formatting:

name = "Alice"
age = 25
formatted_string = f"My name is {name} and I am {age} years old."
print(formatted_string)

# Checking if a substring exists:

my_string = "Hello, World!"
print("Hello" in my_string)
print("foo" in my_string)





Hello World
World
hello, world!
HELLO, WORLD!
My name is Alice and I am 25 years old.
True
False


In [ ]:
# Checking whether a string is substring to other or not:
s1 = input("Enter the first string: ")
s2 = input("Enter the second string: ")

i = 0
j = 0

while i < len(s1) and j < len(s2):
    if s1[i] == s2[j]:
        j += 1
    i += 1

if j == len(s2):
    print("YES")
else:
    print("NO")



Enter the first string: welcome
Enter the second string: home
NO


In [ ]:
# List and its operation:

# Appending elements:

my_list = [1, 2, 3, 4, 5]
my_list.append(6)
print(my_list)

# Checking membership:

my_list = [1, 2, 3, 4, 5]
print(3 in my_list)
print(6 in my_list)

# List concatenation:

list1 = [1, 2, 3]
list2 = [4, 5, 6]
concatenated_list = list1 + list2
print(concatenated_list)

# List slicing:

my_list = [1, 2, 3, 4, 5]
print(my_list[1:4])
print(my_list[:3])
print(my_list[2:])








[1, 2, 3, 4, 5, 6]
True
False
[1, 2, 3, 4, 5, 6]
[2, 3, 4]
[1, 2, 3]
[3, 4, 5]


In [ ]:
# Positive and negative indexing :

lst = ['a', 'b', 'c', 'd', 'e']

# Positive indexing
print("Positive indexing:")
for i in range(len(lst)):
    print("Index", i, ": Element", lst[i])

# Negative indexing
print("\nNegative indexing:")
for i in range(-len(lst), 0):
    print("Index", i, ": Element", lst[i])


Positive indexing:
Index 0 : Element a
Index 1 : Element b
Index 2 : Element c
Index 3 : Element d
Index 4 : Element e

Negative indexing:
Index -5 : Element a
Index -4 : Element b
Index -3 : Element c
Index -2 : Element d
Index -1 : Element e


In [ ]:
# Checking given list is ascending order or not:

def is_ascending(lst):
    for i in range(len(lst) - 1):
        if lst[i] > lst[i + 1]:
            return False
    return True


nums = [1, 2, 3, 4, 5]

if is_ascending(nums):
    print("The list is in ascending order.")
else:
    print("The list is not in ascending order.")



The list is in ascending order.


In [ ]:
# Tuples ad its operations :

# Length of tuple:

my_tuple = (1, 2, 3)
print(len(my_tuple))

# Concateation:

tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
concatenated_tuple = tuple1 + tuple2
print(concatenated_tuple)

# Slicing:

my_tuple = (1, 2, 3, 4, 5)
print(my_tuple[1:4])
print(my_tuple[:3])
print(my_tuple[2:])

# Checking for membership :

my_tuple = (1, 2, 3)
print(2 in my_tuple)
print(4 in my_tuple)




3
(1, 2, 3, 4, 5, 6)
(2, 3, 4)
(1, 2, 3)
(3, 4, 5)
True
False


In [ ]:
# Converting tuple to a string :

def tuple_to_string(t):
    string_representation = ""
    for item in t:
        string_representation += str(item)
    return string_representation

my_tuple = (1, 2, 3, 4, 5)

string_output = tuple_to_string(my_tuple)
print(string_output)


12345


In [ ]:
# Reversing a tuple :

def reverse_tuple(t):
    reversed_tuple = t[::-1]
    return reversed_tuple

my_tuple = (1, 2, 3, 4, 5)

reversed_output = reverse_tuple(my_tuple)
print(reversed_output)


(5, 4, 3, 2, 1)


In [ ]:
# Sets ad its operations:

# checking membership:

my_set = {1, 2, 3}
print(2 in my_set)
print(4 in my_set)

# Set operations:

set1 = {1, 2, 3}
set2 = {3, 4, 5}

union_set = set1.union(set2)
intersection_set = set1.intersection(set2)
difference_set = set1.difference(set2)
symmetric_difference_set = set1.symmetric_difference(set2)

# Length of set :

my_set = {1, 2, 3}
print(len(my_set))





True
False
3


In [ ]:
# Checking if a set is a subset of another set

def is_subset(set1, set2):
    return set1.issubset(set2)

set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}

if is_subset(set1, set2):
    print("set1 is a subset of set2")
else:
    print("set1 is not a subset of set2")


set1 is a subset of set2


In [ ]:
# Dictionaries and its operations :

# Adding new key-value pairs:

my_dict = {"name": "John", "age": 25, "city": "New York"}
my_dict["occupation"] = "Engineer"

# Checking if a key exists:

my_dict = {"name": "John", "age": 25, "city": "New York"}
print("age" in my_dict)
print("country" in my_dict)

# Iterating over keys and values:

my_dict = {"name": "John", "age": 25, "city": "New York"}
for key in my_dict:
    print(key, my_dict[key])

#  Dictionary comprehension:

my_dict = {x: x**2 for x in range(1, 6)}
print(my_dict)




True
False
name John
age 25
city New York
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
# Iterating over dictionaries using for loops:

my_dict = {"name": "John", "age": 25, "city": "New York"}

# Iterating over keys
print("Keys:")
for key in my_dict:
    print(key)

# Iterating over values
print("\nValues:")
for value in my_dict.values():
    print(value)

# Iterating over key-value pairs
print("\nKey-Value Pairs:")
for key, value in my_dict.items():
    print(key, ":", value)


Keys:
name
age
city

Values:
John
25
New York

Key-Value Pairs:
name : John
age : 25
city : New York


In [18]:
# Computations using NumPy functions

import numpy as np

# Create NumPy arrays:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

add_result = a + b
subtract_result = a - b
multiply_result = a * b
divide_result = a / b
power_result = a ** b

# Dot product
dot_product_result = np.dot(a, b)

# Transpose of an array
c = np.array([[1, 2], [3, 4], [5, 6]])
transpose_result = c.T

# Statistical computations
data = np.array([3, 5, 8, 12, 7, 10, 6])
mean_value = np.mean(data)
median_value = np.median(data)
std_deviation = np.std(data)


# Reshape an array
original_array = np.arange(1, 10)
reshaped_array = original_array.reshape(3, 3)

# Array slicing
my_array = np.array([10, 20, 30, 40, 50, 60])
sliced_array = my_array[1:4]




In [5]:
# NumPy program to convert a list of numeric value into a one-dimensional NumPy array

import numpy as np

numeric_list = [3, 9, 7, 4, 1]

# Convert the list to a one-dimensional NumPy array
numeric_array = np.array(numeric_list)

print("Original list:", numeric_list)
print("One-dimensional NumPy array:", numeric_array)


Original list: [1, 2, 3, 4, 5]
One-dimensional NumPy array: [1 2 3 4 5]


In [11]:
# NumPy program to convert a list and tuple into arrays.


# Sample list and tuple
my_list = [1, 2, 3, 4, 5]
my_tuple = (6, 7, 8, 9, 10)

# Convert the list and tuple to NumPy arrays
list_array = np.array(my_list)
tuple_array = np.array(my_tuple)

print("Original list:", my_list)
print("List as NumPy array:", list_array)

print("\nOriginal tuple:", my_tuple)
print("Tuple as NumPy array:", tuple_array)


Original list: [1, 2, 3, 4, 5]
List as NumPy array: [1 2 3 4 5]

Original tuple: (6, 7, 8, 9, 10)
Tuple as NumPy array: [ 6  7  8  9 10]


In [7]:
# Data manipulations using Pandas.

import pandas as pd

data = {
    'Name': ['Sam', 'Parthi', 'Ramesh', 'Rahul', 'Veer'],
    'Age': [22, 43, 21, 42, 39],
    'City': ['Tuticorin', 'Chennai', 'Nilgris', 'Erode', 'Vellore']
}

df = pd.DataFrame(data)
print(df)



      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   35     Tokyo
4    Emily   28    Sydney


In [14]:
# Program to convert a NumPy array and series to data frames.

# Convert a NumPy array to a DataFrame
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_numpy = pd.DataFrame(numpy_array, columns=['A', 'B', 'C'])

print("NumPy Array:")
print(numpy_array)
print("\nDataFrame from NumPy Array:")
print(df_from_numpy)

# Convert a Pandas Series to a DataFrame
pandas_series = pd.Series([10, 20, 30, 40, 50], name='Values')
df_from_series = pd.DataFrame(pandas_series)

print("\nPandas Series:")
print(pandas_series)
print("\nDataFrame from Pandas Series:")
print(df_from_series)


NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

DataFrame from NumPy Array:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Pandas Series:
0    10
1    20
2    30
3    40
4    50
Name: Values, dtype: int64

DataFrame from Pandas Series:
   Values
0      10
1      20
2      30
3      40
4      50


In [13]:
# Program to add, subtract, multiple and divide two Pandas Series.

# Create two Pandas Series
series1 = pd.Series([11, 2, 22, 43, 14], name='Series1')
series2 = pd.Series([2, 4, 6, 8, 10], name='Series2')

add_result = series1 + series2
subtract_result = series1 - series2
multiply_result = series1 * series2
divide_result = series1 / series2

# Combine the results into a DataFrame
result_df = pd.DataFrame({
    'Series1': series1,
    'Series2': series2,
    'Addition': add_result,
    'Subtraction': subtract_result,
    'Multiplication': multiply_result,
    'Division': divide_result
})

print(result_df)


   Series1  Series2  Addition  Subtraction  Multiplication  Division
0       11        2        13            9              22  5.500000
1        2        4         6           -2               8  0.500000
2       22        6        28           16             132  3.666667
3       43        8        51           35             344  5.375000
4       14       10        24            4             140  1.400000


In [15]:
# Program to retrieve and manipulate data using dataframes.

# Create a sample DataFrame
data = {
    'Name': ['Ram', 'Prakash', 'Karthi', 'Aadhik', 'Shyam'],
    'Age': [25, 30, 22, 35, 28],
    'City': ['Trichy', 'Coimbatore', 'Chennai', 'Madurai', 'Ooty'],
    'Salary': [50000, 60000, 45000, 70000, 55000]
}

df = pd.DataFrame(data)

# 1. Display the entire DataFrame
print("Entire DataFrame:")
print(df)

# 2. Select specific columns
selected_columns = df[['Name', 'City']]
print("\nSelected columns:")
print(selected_columns)

# 3. Filter rows based on a condition
filtered_data = df[df['Age'] < 30]
print("\nPeople under 30:")
print(filtered_data)

# 4. Sort the DataFrame
sorted_data = df.sort_values(by='Salary', ascending=False)
print("\nSorted by Salary:")
print(sorted_data)

# 5. Aggregation: Calculate average salary
average_salary = df['Salary'].mean()
print("\nAverage Salary:", average_salary)

# 6. Adding a new column
df['Bonus'] = df['Salary'] * 0.1
print("\nDataFrame with Bonus column:")
print(df)

# 7. Removing a column
df.drop(columns='City', inplace=True)
print("\nDataFrame after removing the City column:")
print(df)

# 8. Grouping data and applying aggregation functions
grouped_data = df.groupby('Age').mean()
print("\nGrouped data by Age with average values:")
print(grouped_data)


Entire DataFrame:
      Name  Age        City  Salary
0      Ram   25      Trichy   50000
1  Prakash   30  Coimbatore   60000
2   Karthi   22     Chennai   45000
3   Aadhik   35     Madurai   70000
4    Shyam   28        Ooty   55000

Selected columns:
      Name        City
0      Ram      Trichy
1  Prakash  Coimbatore
2   Karthi     Chennai
3   Aadhik     Madurai
4    Shyam        Ooty

People under 30:
     Name  Age     City  Salary
0     Ram   25   Trichy   50000
2  Karthi   22  Chennai   45000
4   Shyam   28     Ooty   55000

Sorted by Salary:
      Name  Age        City  Salary
3   Aadhik   35     Madurai   70000
1  Prakash   30  Coimbatore   60000
4    Shyam   28        Ooty   55000
0      Ram   25      Trichy   50000
2   Karthi   22     Chennai   45000

Average Salary: 56000.0

DataFrame with Bonus column:
      Name  Age        City  Salary   Bonus
0      Ram   25      Trichy   50000  5000.0
1  Prakash   30  Coimbatore   60000  6000.0
2   Karthi   22     Chennai   45000  4500

<ipython-input-15-87b6200060d4>:47: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_data = df.groupby('Age').mean()
